// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_xtL9CUmB0SdldEm8w0pceT-9qvJJh8I',
    appId: '1:443992564565:web:0c749ecad3ac4ab3ffc5dc',
    messagingSenderId: '443992564565',
    projectId: 'minara-8ee8c',
    authDomain: 'minara-8ee8c.firebaseapp.com',
    storageBucket: 'minara-8ee8c.firebasestorage.app',
    measurementId: 'G-KXRBGF95SR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3lb31BosQCnDAxnBJ_PB0nT-xlzEqHkg',
    appId: '1:443992564565:android:ff2c10acfd270208ffc5dc',
    messagingSenderId: '443992564565',
    projectId: 'minara-8ee8c',
    storageBucket: 'minara-8ee8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgeR_hRMRvwRunbTqeiQHhOSC1AYVkLt8',
    appId: '1:443992564565:ios:f38d520150c4ff39ffc5dc',
    messagingSenderId: '443992564565',
    projectId: 'minara-8ee8c',
    storageBucket: 'minara-8ee8c.firebasestorage.app',
    iosBundleId: 'com.example.pooper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgeR_hRMRvwRunbTqeiQHhOSC1AYVkLt8',
    appId: '1:443992564565:ios:f38d520150c4ff39ffc5dc',
    messagingSenderId: '443992564565',
    projectId: 'minara-8ee8c',
    storageBucket: 'minara-8ee8c.firebasestorage.app',
    iosBundleId: 'com.example.pooper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_xtL9CUmB0SdldEm8w0pceT-9qvJJh8I',
    appId: '1:443992564565:web:8312a684eca26e2dffc5dc',
    messagingSenderId: '443992564565',
    projectId: 'minara-8ee8c',
    authDomain: 'minara-8ee8c.firebaseapp.com',
    storageBucket: 'minara-8ee8c.firebasestorage.app',
    measurementId: 'G-EK2EQXLSP2',
  );

}